config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :role_permissions
  resources :permissions
  resources :bookings
  resources :shows do
    resources :bookings
  end
  resources :theatres do
    resources :shows
  end
  resources :reviews
  devise_for :users
  resources :movies do
    resources :reviews, except: [:show, :index]
  end

  get '/rbac', to: 'roles#management'
  get '/assign', to: 'assign#users'

  get '/assign/:user_id', to: 'assign#assign'

  post '/assign/:user_id', to: 'assign#assign'

  root to: "movies#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user = user || User.new
    permissions(user)
  end

  def permissions(user)
    role = user.role
    if user.role.nil?
      can :read, :all #for guest without roles
    else
      File.readlines("permissions/#{role.downcase}.rb").each do |f|
        eval(f)
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
  #has_paper_trail

  def self.destroy_record(user_id, role_id)
    ActiveRecord::Base.connection.execute("update assignments set active=1 where assignments.user_id=#{current_user.id} AND assignments.role_id=#{x.to_i}")
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_permissions
  has_many :roles, :through => :role_permissions
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/role.rb
class Role < ApplicationRecord

  has_many :assignments
  has_many :users, :through => :assignments

  has_many :role_permissions
  has_many :permissions, :through => :role_permissions

end

app/models/role_permission.rb
class RolePermission < ApplicationRecord
  belongs_to :permission
  belongs_to :role
end

app/models/seat.rb
class Seat < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :theatre

  has_many :bookings
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :shows, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :assignments
  has_many :roles, :through => :assignments
  has_many :designation_mappings

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  before_action :set_theatre, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /theatres
  # GET /theatres.json
  def index
    @theatres = Theatre.all
  end

  # GET /theatres/1
  # GET /theatres/1.json
  def show
    @shows = Show.where(theatre_id: @theatre.id).order("created_at DESC")
  end

  # GET /theatres/new
  def new
    @theatre = Theatre.new
  end

  # GET /theatres/1/edit
  def edit
  end

  # POST /theatres
  # POST /theatres.json
  def create
    @theatre = Theatre.new(theatre_params)
    @theatre.manager_id = params[:manager_id]
    @theatre.save
    respond_to do |format|
      if @theatre.save
        format.html { redirect_to @theatre, notice: 'Theatre was successfully created.' }
        format.json { render :show, status: :created, location: @theatre }
      else
        format.html { render :new }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theatres/1
  # PATCH/PUT /theatres/1.json
  def update
    respond_to do |format|
      if @theatre.update(theatre_params)
        format.html { redirect_to @theatre, notice: 'Theatre was successfully updated.' }
        format.json { render :show, status: :ok, location: @theatre }
      else
        format.html { render :edit }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatres/1
  # DELETE /theatres/1.json
  def destroy
    @theatre.destroy
    respond_to do |format|
      format.html { redirect_to theatres_url, notice: 'Theatre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theatre
      @theatre = Theatre.find(params[:id])
      @theatre_manager = User.where(:id=>@theatre.manager_id).first;
      @all_movies_ids = Show.where(:theatre_id=>@theatre.id).pluck(:movie_id)
      @all_movies = Movie.where(:id => @all_movies_ids).pluck(:id,:title)
    end



  # Never trust parameters from the scary internet, only allow the white list through.
    def theatre_params
      params.require(:theatre).permit(:name, :capacity, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/theatres/_form.html.erb
<%= form_with(model: theatre, local: true) do |form| %>

  <div class="field">
    <div class="row">
      <div class="form-group col-lg-6">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control color' %>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="row">
      <div class="form-group col-lg-6">
        <%= form.label :capacity %>
        <%= form.number_field :capacity, class: 'form-control color' %>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="row">
      <div class="form-group col-lg-6">
        <%= form.label :address %>
        <%= form.text_area :address, class: 'form-control color' %>
      </div>
    </div>
  </div>


  <div class="field">
    <% @users = User.where(:role => "manager") %>
    <div class="row">
      <div class="form-group col-lg-6">
        <%= form.label :manager_id %>
        <%= select_tag :manager_id, options_from_collection_for_select(@users, "id", "email"), :class=>"form-control"  %>
      </div>
    </div>
  </div>



  <div class="actions">
    <%= form.submit class: "btn btn-success btn-lg" %>
  </div>

<% end %>

app/views/theatres/edit.html.erb
<h1>Editing Theatre</h1>

<%= render 'form', theatre: @theatre %>

<%= link_to 'Show', @theatre %> |
<%= link_to 'Back', theatres_path %>

app/views/theatres/index.html.erb
<p id="notice"><%= notice %></p>


<h1 id="title">Theatres</h1>

<hr>
<div class="container" style="width: 90%; margin-left: 0">
  <table class="dataTable table table-striped " id="dttb">
    <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th>Address</th>
      <th>Manager</th>
      <th> Actions</th>
    </tr>
    </thead>

    <tbody>

    <% managers= User.where(:role=>"manager")%>
    <% @theatres.each do |theatre| %>
      <% manager= managers.select {|x| x.id == theatre.manager_id} %>
      <tr>
        <td><%= theatre.name %></td>
        <td><%= theatre.capacity %></td>
        <td><%= theatre.address %></td>
        <td><%= manager[0].email %>        </td>
        <% if  can? :update, Theatre  %>
          <td><%= link_to 'Show', theatre, :class => "btn btn-primary" %>
          <%= link_to 'Edit', edit_theatre_path(theatre), :class => "btn btn-primary" %>
            <% if can? :destroy, Theatre %>
              <%= link_to 'Destroy', theatre, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger" %></td>
            <% end %>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>
<% if can? :manage, Theatre %>
  <%= link_to "New Theatre".html_safe, new_theatre_path, :class => "btn btn-info " %>
<% end %>


<script>
    $(document).ready(function () {
        $("#dttb").dataTable({
                width: 80,
                responsive: true
            }
        );
    });

</script>

app/views/theatres/new.html.erb
<h1>Add a Theatre</h1>
<hr>
<%= render 'form', theatre: @theatre %>


<br>
<%= link_to "BACK".html_safe, theatres_path, :class => "btn btn-default " %>

app/views/theatres/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container1">
<h1>
  <%= @theatre.name %>
</h1>
<hr>
<p>
  <strong>Capacity:</strong>
  <%= @theatre.capacity %>
</p>

<p>
  <strong>Address:</strong>
  <%= @theatre.address %>
</p>


<% if @shows.blank? %>
  <p>No movies playing here currently</p>
<% else %>
    <table class="table-striped table">
      <thead>
      <tr>
        <th>Movie</th>
        <th>Show Time</th>
        <th>Action</th>
      </tr>
      </thead>

      <tbody>
      <% @shows.each do |show| %>
        <tr>
          <td><%= @all_movies.select {|x| x[0]==show.movie_id}.first[1] %></td>
          <td><%= show.start.strftime("%a %d %b %l:%M %p") %></td>
          <td><%= link_to "Book", new_show_booking_path(show), class:"btn btn-primary"%></td>
        </tr>

      <% end %>
      </tbody>
    </table>
<% end %>


  <% if current_user.admin? or current_user.id = @theatre.manager_id %>
<%= link_to "Add a Show", new_theatre_show_path(@theatre), :class=>"btn btn-success btn-lg" %>
  <br><br>
<%= link_to 'Edit', edit_theatre_path(@theatre) , :class=>"btn btn-default" %>
<%end%>

  <%= link_to 'Back', theatres_path,:class=>"btn btn-default"  %>
</div>