config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :role_permissions
  resources :permissions
  resources :bookings
  resources :shows do
    resources :bookings
  end
  resources :theatres do
    resources :shows
  end
  resources :reviews
  devise_for :users
  resources :movies do
    resources :reviews, except: [:show, :index]
  end

  get '/rbac', to: 'roles#management'
  get '/assign', to: 'assign#users'

  get '/assign/:user_id', to: 'assign#assign'

  post '/assign/:user_id', to: 'assign#assign'

  root to: "movies#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user = user || User.new
    permissions(user)
  end

  def permissions(user)
    role = user.role
    if user.role.nil?
      can :read, :all #for guest without roles
    else
      File.readlines("permissions/#{role.downcase}.rb").each do |f|
        eval(f)
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
  #has_paper_trail

  def self.destroy_record(user_id, role_id)
    ActiveRecord::Base.connection.execute("update assignments set active=1 where assignments.user_id=#{current_user.id} AND assignments.role_id=#{x.to_i}")
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_permissions
  has_many :roles, :through => :role_permissions
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/role.rb
class Role < ApplicationRecord

  has_many :assignments
  has_many :users, :through => :assignments

  has_many :role_permissions
  has_many :permissions, :through => :role_permissions

end

app/models/role_permission.rb
class RolePermission < ApplicationRecord
  belongs_to :permission
  belongs_to :role
end

app/models/seat.rb
class Seat < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :theatre

  has_many :bookings
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :shows, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :assignments
  has_many :roles, :through => :assignments
  has_many :designation_mappings

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

end

app/controllers/role_permissions_controller.rb
class RolePermissionsController < ApplicationController
  before_action :set_role_permission, only: [:show, :edit, :update, :destroy]

  # GET /role_permissions
  # GET /role_permissions.json
  def index
    @role_permissions = RolePermission.all
    @roles = Role.all
    @permissions = Permission.all

  end

  # GET /role_permissions/1
  # GET /role_permissions/1.json
  def show
  end

  # GET /role_permissions/new
  def new
    @role_permission = RolePermission.new
    @roles = Role.all
    @permissions = Permission.all
  end

  # GET /role_permissions/1/edit
  def edit
    @roles = Role.all
    @permissions = Permission.all
  end

  # POST /role_permissions
  # POST /role_permissions.json
  def create
    @role_permission = RolePermission.new(role_permission_params)

    respond_to do |format|
      if @role_permission.save
        format.html { redirect_to @role_permission, notice: 'Role permission was successfully created.' }
        format.json { render :show, status: :created, location: @role_permission }
      else
        format.html { render :new }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
    permissions
  end

  # PATCH/PUT /role_permissions/1
  # PATCH/PUT /role_permissions/1.json
  def update
    respond_to do |format|
      if @role_permission.update(role_permission_params)
        format.html { redirect_to @role_permission, notice: 'Role permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @role_permission }
      else
        format.html { render :edit }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
    permissions
  end

  # DELETE /role_permissions/1
  # DELETE /role_permissions/1.json
  def destroy
    @role_permission.destroy
    respond_to do |format|
      format.html { redirect_to role_permissions_url, notice: 'Role permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


  def permissions
    Role.all.each do |role|
      File.open(Rails.root.join("permissions/#{role.name}.rb"), 'w') do |f|
        role.permissions.each do |permission|
          if permission.subject_class[0] == permission.subject_class[0].upcase
            actions=permission.actions.split(',')
            actions.each do |a|
              classes=permission.subject_class.split(',')
              classes.each do |c|
                f.write("can :#{a.to_sym}, #{c.constantize}\n")
              end
            end
          else
            actions=permission.actions.split(',')
            actions.each do |a|
              classes=permission.subject_class.split(',')
              classes.each do |c|
                f.write("can :#{a.to_sym}, :#{c.to_sym}\n")
              end
            end
          end
        end
        puts "Generated permission file for Role: #{role.name}"
      end
    end
  end


    # Use callbacks to share common setup or constraints between actions.
    def set_role_permission
      @role_permission = RolePermission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_permission_params
      params.require(:role_permission).permit(:permission_id, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/role_permissions_helper.rb
module RolePermissionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/role_permissions/_form.html.erb
<div class="col-md-10 col-lg-10">

  <%= bootstrap_form_with(model: role_permission, local: true) do |form| %>
  <% if role_permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role_permission.errors.count, "error") %> prohibited this role_permission from being saved:</h2>

      <ul>
      <% role_permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.select :role_id ,  options_for_select(@roles.order(:name).map {|x| [x.name, x.id]}), prompt: "Select Role"%>
    <%= form.select :permission_id, options_for_select(@permissions.order(:description).map {|x| [x.description, x.id]}),  prompt: "Select Permission" %>
    <%= form.submit "Save", :class => "btn btn-success btn-lg" %>
<% end %>
</div>

app/views/role_permissions/edit.html.erb
<h1>Editing Role Permission</h1>

<hr>
<% role= @roles.select{ |m| m.id == @role_permission.role_id  }.first %>
<% permission= @permissions.select{ |m| m.id == @role_permission.permission_id}.first %>

<h4><%= role.name.capitalize %> |   <%= permission.description %> [ <%= permission.actions %> in <%= permission.subject_class %> ]
</h4>

</h4>


<hr>
<%= render 'form', role_permission: @role_permission %>
<br>
<br><br>
<br>

<div class="col-md-10 col-lg-10">
  <br><br>

<%= link_to 'Show', @role_permission, :class => "btn btn-primary" %>
<%= link_to 'Back', role_permissions_path , :class => "btn btn-info"%>
</div>

app/views/role_permissions/index.html.erb
<h1>Assign Permissions to Roles</h1>
<hr>
<table class="responsive nowrap table table-hover" id="dttb-role_permissions" data-sort="true" data-source="<%= url_for(format: :json) %>">
  <thead>
  <tr>
    <th data-data="role_id">Role</th>
    <th data-data="permission_id">Permission</th>
    <th data-data="actions">Actions</th>

  </tr>
  </thead>

  <tbody>

  <% @role_permissions.each do |rp| %>
    <tr>
      <% role= @roles.select{ |m| m.id == rp.role_id  }.first %>
      <% permission= @permissions.select{ |m| m.id == rp.permission_id}.first %>
      <td><%= role.name.capitalize %></td>
      <td><%= permission.description %> [ <%= permission.actions %> in <%= permission.subject_class %> ]</td>

      <% if  can? :update, RolePermission  %>
        <td>
          <%= link_to 'Edit', edit_role_permission_path(rp), :class => "btn btn-warning" %>
          <% if can? :destroy, RolePermission %>
            <%= link_to 'Destroy', rp, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger" %></td>
          <% end %>
      <% end %>


    </tr>
  <% end %>
  </tbody>


</table>

<br>

<%= link_to 'New Role Permission', new_role_permission_path, :class => "btn btn-primary" %>

app/views/role_permissions/new.html.erb
<h1>New Role Permission</h1>

<%= render 'form', role_permission: @role_permission %>

<%= link_to 'Back', role_permissions_path %>

app/views/role_permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Permission:</strong>
  <%= @role_permission.permission_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @role_permission.role_id %>
</p>

<%= link_to 'Edit', edit_role_permission_path(@role_permission) %> |
<%= link_to 'Back', role_permissions_path %>