config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :role_permissions
  resources :permissions
  resources :bookings
  resources :shows do
    resources :bookings
  end
  resources :theatres do
    resources :shows
  end
  resources :reviews
  devise_for :users
  resources :movies do
    resources :reviews, except: [:show, :index]
  end

  get '/rbac', to: 'roles#management'
  get '/assign', to: 'assign#users'

  get '/assign/:user_id', to: 'assign#assign'

  post '/assign/:user_id', to: 'assign#assign'

  root to: "movies#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user = user || User.new
    permissions(user)
  end

  def permissions(user)
    role = user.role
    if user.role.nil?
      can :read, :all #for guest without roles
    else
      File.readlines("permissions/#{role.downcase}.rb").each do |f|
        eval(f)
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
  #has_paper_trail

  def self.destroy_record(user_id, role_id)
    ActiveRecord::Base.connection.execute("update assignments set active=1 where assignments.user_id=#{current_user.id} AND assignments.role_id=#{x.to_i}")
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_permissions
  has_many :roles, :through => :role_permissions
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/role.rb
class Role < ApplicationRecord

  has_many :assignments
  has_many :users, :through => :assignments

  has_many :role_permissions
  has_many :permissions, :through => :role_permissions

end

app/models/role_permission.rb
class RolePermission < ApplicationRecord
  belongs_to :permission
  belongs_to :role
end

app/models/seat.rb
class Seat < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :theatre

  has_many :bookings
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :shows, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :assignments
  has_many :roles, :through => :assignments
  has_many :designation_mappings

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def management

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/assign.html.erb
<p id="notice"><%= notice %></p>

<h2 id="title">Assign Role for: <%= @user.email %></h2>

<hr>
<div class="container" style="width: 90%; margin-left: 0">
  <%= bootstrap_form_for @user, :url => {:controller => "roles", :action => "assign"}, :method => :POST, :class=>"form-control"  do |f| %>
    <%= f.select :role, options_for_select([ "admin", "producer", "manager","customer", "gold_customer" ], @user.role ), :class=>"form-control" %>
    <%= f.submit "Assign", :class=>"btn btn-primary"%>
  <% end %>

</div>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<div class="col-md-10 col-lg-10">
<h1>Roles</h1>
<hr>
<table class="responsive nowrap table table-hover" id="dttb-roles" data-sort="true" data-source="<%= url_for(format: :json)%>">
  <thead>
    <tr>
      <th data-data="name">Name</th>
      <th data-data="description">Description</th>
      <th data-data="actions">Actions</th>
    </tr>
  </thead>

  <tbody>

  <% @roles.each do |role| %>
    <tr>
      <td><%= role.name.capitalize %></td>
      <td><%= role.description %></td>
      <% if  can? :update, Role  %>
        <td>
          <%= link_to 'Edit', edit_role_path(role), :class => "btn btn-warning" %>
          <% if can? :destroy, Role %>
            <%= link_to 'Destroy', role, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger" %></td>
          <% end %>
      <% end %>
    </tr>
  <% end %>
  </tbody>


</table>

<br>

<%= link_to 'New Role', new_role_path, :class => "btn btn-primary" %>

</div>

app/views/roles/management.html.erb
<h1>Role Based Access Control</h1>
<hr>

<%= link_to 'Manage Roles', roles_path, :class => "btn btn-primary" %>
<%= link_to 'Manage Permissions', permissions_path, :class => "btn btn-primary" %>
<%= link_to 'Assign Permission to Roles', role_permissions_path, :class => "btn btn-primary" %>
<%= link_to 'Assign Roles to Users', assign_path, :class => "btn btn-primary" %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/roles/users.html.erb
<h1 id="title">Assign Roles</h1>
<p id="notice"><%= notice %></p>

<hr>
<div class="container" style="width: 90%; margin-left: 0">

  <table class="dataTable table table-striped " id="dttb">
    <thead>
    <tr>
      <th>E-Mail</th>
      <th>Role</th>
      <th>Action</th>

    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role.capitalize! if user.role? %></td>
        <td>
          <%= link_to "Assign", {:controller => "roles", :action => "assign", :user_id => user.id }, :class => "btn btn-primary"%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>


<script>
    $(document).ready(function () {
        $("#dttb").dataTable({
                width: 80,
                responsive: true
            }
        );
    });

</script>