config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :role_permissions
  resources :permissions
  resources :bookings
  resources :shows do
    resources :bookings
  end
  resources :theatres do
    resources :shows
  end
  resources :reviews
  devise_for :users
  resources :movies do
    resources :reviews, except: [:show, :index]
  end

  get '/rbac', to: 'roles#management'
  get '/assign', to: 'assign#users'

  get '/assign/:user_id', to: 'assign#assign'

  post '/assign/:user_id', to: 'assign#assign'

  root to: "movies#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user = user || User.new
    permissions(user)
  end

  def permissions(user)
    role = user.role
    if user.role.nil?
      can :read, :all #for guest without roles
    else
      File.readlines("permissions/#{role.downcase}.rb").each do |f|
        eval(f)
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
  #has_paper_trail

  def self.destroy_record(user_id, role_id)
    ActiveRecord::Base.connection.execute("update assignments set active=1 where assignments.user_id=#{current_user.id} AND assignments.role_id=#{x.to_i}")
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_permissions
  has_many :roles, :through => :role_permissions
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/role.rb
class Role < ApplicationRecord

  has_many :assignments
  has_many :users, :through => :assignments

  has_many :role_permissions
  has_many :permissions, :through => :role_permissions

end

app/models/role_permission.rb
class RolePermission < ApplicationRecord
  belongs_to :permission
  belongs_to :role
end

app/models/seat.rb
class Seat < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :theatre

  has_many :bookings
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :shows, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :assignments
  has_many :roles, :through => :assignments
  has_many :designation_mappings

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top example-8">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand text-hide" href="#">Movie Portal</a>
    </div>

    <div class="navbar-header pull-right">
      <h4 style="color: white"><b><%= current_user.email if current_user %> </b>| <%= current_user.role.capitalize! if current_user %></h4>
    </div>
  </div>
</nav>

<nav class="sidebar-navigation">
  <ul>
    <%= link_to root_path do %>
      <li>
        <i class="fa fa-home"></i>
        <span class="tooltip">Home</span>
      </li>
    <% end %>

    <%= link_to movies_path do %>

      <li>
        <i class="fa fa-film"></i>
        <span class="tooltip">Movies</span>
      </li>
    <% end %>


    <%= link_to theatres_path do %>

      <li>
        <i class="fa fa-building"></i>
        <span class="tooltip">Theatres</span>
      </li>

    <% end %>

    <% if user_signed_in? %>

      <%= link_to bookings_path do %>
        <li>
          <i class="fa fa-ticket"></i>
          <span class="tooltip">My Tickets</span>
        </li>

      <% end %>


      <% if can? :manage, Movie %>

        <%= link_to new_movie_path do %>
          <li>
            <i class="fa fa-plus"></i>
            <span class="tooltip">New Movies</span>
          </li>

        <% end %>
      <% end %>

      <% if can? :manage, Theatre %>
        <%= link_to new_theatre_path do %>

          <li>
            <i class="fa fa-plus-square"></i>
            <span class="tooltip">New Theatres</span>
          </li>

        <% end %>

      <% end %>


      <%= link_to edit_user_registration_path do %>
        <li>
          <i class="fa fa-user"></i>
          <span class="tooltip">My Profile</span>
        </li>

      <% end %>

      <% if can? :manage, User %>
        <%= link_to rbac_path do %>
          <li>
            <i class="fa fa-users"></i>
            <span class="tooltip">RBAC</span>
          </li>

        <% end %>
      <% end %>


      <%= link_to(destroy_user_session_path, method: :delete) do %>
        <li>
          <i class="fa fa-sign-out"></i>
          <span class="tooltip">Logout</span>
        </li>

      <% end %>


    <% else %>

      <%= link_to new_user_session_path do %>
        <li>
          <i class="fa fa-sign-in"></i>
          <span class="tooltip">Login</span>
        </li>
      <% end %>

    <% end %>

  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Central</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('fav.ico'), :rel => 'icon', :type =>  'image/ico' %>
</head>

<body>
<%= render 'layouts/header' %>
<div class="container card">


<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>

</div>
</div>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
</body>
</html>